### ISSUE TITLE
Publish a new version of Microsoft.DiaSymReader to nuget.org

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/symreader#282]
As noted in https://github.com/dotnet/symreader/pull/261#issuecomment-1515938744, a new version of Microsoft.DiaSymReader hasn't shipped for more than a year and is missing the `netstandard2.0` TFM upgrade.

The latest package version on nuget.org brings in NETStandard.Library/1.6.1 which itself transitively brings in the entire .NET Standard 1.6 dependency graph (which is huge). That graph might contains either deprecated or vulnerable packages which we haven't been touched for years.

I noticed this as I looked into a package that depends on Microsoft.DiaSymReader and the reference caused Component Governance warnings.

**Comment by ViktorHofer** [comment]
cc @tmat @jaredpar @mmitche

**Comment by jaredpar** [comment]
Yeah I just hit the exact same Component Governance issue on another repo and the root cause is DiaSymReader.

**Comment by mmitche** [comment]
Yeah we should do this.

**Comment by ViktorHofer** [comment]
Got pushed at some point during the release cycle. Closing.
