### ISSUE TITLE
Dependencies need to be updated

### ISSUE THREAD

**Issue by davidfowl** [dotnet/symreader#9]
https://github.com/dotnet/symreader/blob/master/src/Microsoft.DiaSymReader/Microsoft.DiaSymReader.nuspec#L10-L15

To at least `rc2-23931`

/cc @agocke

**Comment by tmat** [comment]
I'll update it.

**Comment by tmat** [comment]
Fixed: 

http://www.myget.org/F/roslyn-nightly/api/v2/package/Microsoft.DiaSymReader/1.0.8-rc2-60406-06
